drop table Article if exists;
drop table ArticleComment if exists;
create table Article (id bigint generated by default as identity, contents varchar(255), date timestamp, title varchar(255), primary key (id));
create table ArticleComment (id bigint generated by default as identity, comment varchar(255), importance integer not null, article_id bigint, primary key (id));
alter table ArticleComment add constraint FK2yhodfwcna08ir06ke6mysbfw foreign key (article_id) references Article;
